# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solutionDirectory: 'unit-testing-aspnetcore-webapi/netcore-unit-testing/web-api.sln'
  sourceCodeProjectPath: 'web-api/web-api.csproj'
  unitTestProjectPath: 'web-api-tests/web-api-tests.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: $(unitTestProjectPath)
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet build [$(solutionDirectory)] --configuration $(buildConfiguration)
  displayName: dotnet build $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(sourceCodeProjectPath)
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
