# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solutionDirectory: 'netcore-unit-testing/web-api.sln'
  sourceCodeProjectPath: 'netcore-unit-testing/web-api/web-api.csproj'
  unitTestProjectPath: 'netcore-unit-testing/web-api-tests/web-api-tests.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'drop'

steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: test
    projects: '$(unitTestProjectPath)'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet build $(solutionDirectory) --configuration $(buildConfiguration)
  displayName: 'DotNet Build $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  displayName: 'DotNet Publish $(buildConfiguration) -> $(Build.ArtifactStagingDirectory)\drop'
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(sourceCodeProjectPath)
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: $(artifactName)
    publishLocation: Container

- download: current
  artifact: Container $(artifactName)